Expose cvm Ins and Outs
ava-labs/ortelius pull request #226
Opened 2020-12-21 15:38 UTC by tasinco

2020-12-22 06:26 UTC, tyler-smith approved these changes
Edit: Commented on wrong PR.

2020-12-22 06:40 UTC, tyler-smith requested changes
Some questions to discuss.

2020-12-22 06:40 UTC, tyler-smith commented on services/indexes/models/avax.go
> +type CvmOutput struct {
What is the reason for creating a separate Output struct? At least c chain import inputs and c chain export outputs are the same type of Outpoint in the protocol as any other x or p chain  outpoint.

2020-12-22 06:40 UTC, tyler-smith commented on services/indexes/models/types.go
> +type CChainType uint16
Same as the model bit with these types, why not make them part of the existing transaction and output types?

2020-12-23 18:42 UTC, tasinco commented
we'll do https://github.com/ava-labs/ortelius/pull/228 instead.

2020-12-23 18:42 UTC, closed without merging