update versions
ava-labs/ortelius pull request #464
Opened 2022-04-14 19:37 UTC by learyce

2022-04-14 20:04 UTC, dhrubabasu requested changes
Need to update the dockerfile to go v1.17.9

2022-04-19 16:37 UTC, learyce commented
> Need to update the dockerfile to go v1.17.9

Yep, wanted to use the test suite that's run on PR creation to confirm nothing was broken.  Now ready for an actual review

2022-04-19 16:43 UTC, StephenButtolph approved these changes
LGTM

2022-04-19 16:46 UTC, dhrubabasu approved these changes

2022-04-19 16:49 UTC, merged